import { ReactNode } from 'react'
import type { Metadata } from 'next'
import Link from 'next/link'
import Image from 'next/image'
import { Analytics } from '@vercel/analytics/react'

// Styles
import './styles/globals.css'
import styles from './styles/layout.module.css'
import { merienda } from './styles/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <body className={`${merienda.className} antialiased`}>
        <header className={styles.header}>
          <nav>
            <Link href='/'>
              <Image
                className={styles.logoContainer}
                alt='Imagen de portada'
                height={164}
                src='/images/logo.png'
                width={450}
              />
            </Link>
          </nav>
        </header>

        <main>{children}</main>

        <Analytics />
      </body>
    </html>
  )
}
